/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-17 08:18:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("\tDimension by HTML5 UP\r\n");
      out.write("\thtml5up.net | @ajlkn\r\n");
      out.write("\tFree for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>그린전자</title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/assets/css/main.css\" />\r\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"/resources/assets/css/noscript.css\" /></noscript>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Wrapper -->\r\n");
      out.write("\t\t\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon fa-gem\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>그린전자</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>그린전자에 오신 것을 환영합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#intro\">Intro</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#work\">Work</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <li><a href=\"#about\">About</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--<li><a href=\"#elements\">Elements</a></li>-->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Intro -->\r\n");
      out.write("\t\t\t\t\t\t\t<article id=\"intro\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"major\">Intro</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"image main\"><img src=\"images/pic01.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>회사 소개</p>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Work -->\r\n");
      out.write("\t\t\t\t\t\t\t<article id=\"work\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"major\">Work</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"image main\"><img src=\"images/pic02.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>하는일 엘베 고치깅 </p>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- About -->\r\n");
      out.write("\t\t\t\t\t\t\t<article id=\"about\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"major\">About</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"image main\"><img src=\"images/pic03.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur et adipiscing elit. Praesent eleifend dignissim arcu, at eleifend sapien imperdiet ac. Aliquam erat volutpat. Praesent urna nisi, fringila lorem et vehicula lacinia quam. Integer sollicitudin mauris nec lorem luctus ultrices. Aliquam libero et malesuada fames ac ante ipsum primis in faucibus. Cras viverra ligula sit amet ex mollis mattis lorem ipsum dolor sit amet.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Contact -->\r\n");
      out.write("\t\t\t\t\t\t\t<article id=\"contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"major\">Contact</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fields\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"message\">ph.</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>010-2057-7676</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fields\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"name\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"email\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"email\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"message\">Message</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"message\" id=\"message\" rows=\"4\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" class=\"primary\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Reset\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-github\"><span class=\"label\">GitHub</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Elements -->\r\n");
      out.write("\t\t\t\t\t\t\t<article id=\"elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"major\">Elements</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"major\">Text</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThis is <sup>superscript</sup> text and this is <sub>subscript</sub> text.\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThis is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>. Finally, <a href=\"#\">this is a link</a>.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Heading Level 2</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Heading Level 3</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Heading Level 4</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5>Heading Level 5</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6>Heading Level 6</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Blockquote</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</blockquote>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Preformatted</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<pre><code>i = 0;\r\n");
      out.write("\r\n");
      out.write("while (!deck.isInOrder()) {\r\n");
      out.write("    print 'Iteration ' + i;\r\n");
      out.write("    deck.shuffle();\r\n");
      out.write("    i++;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("print 'It took ' + i + ' iterations to sort the deck.';</code></pre>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"major\">Lists</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Unordered</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Dolor pulvinar etiam.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Sagittis adipiscing.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Felis enim feugiat.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Alternate</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Dolor pulvinar etiam.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Sagittis adipiscing.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Felis enim feugiat.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Ordered</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Dolor pulvinar etiam.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Etiam vel felis viverra.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Felis enim feugiat.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Dolor pulvinar etiam.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Etiam vel felis lorem.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Felis enim et feugiat.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Icons</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-github\"><span class=\"label\">Github</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Actions</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions stacked\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"major\">Table</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Default</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item One</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Two</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Vis ac commodo adipiscing arcu aliquet.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>19.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Three</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td> Morbi faucibus arcu accumsan lorem.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Four</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Vitae integer tempus condimentum.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>19.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Five</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>100.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Alternate</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item One</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Two</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Vis ac commodo adipiscing arcu aliquet.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>19.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Three</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td> Morbi faucibus arcu accumsan lorem.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Four</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Vitae integer tempus condimentum.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>19.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Item Five</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>29.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>100.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"major\">Buttons</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Primary</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button small\">Small</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary icon solid fa-download\">Icon</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button icon solid fa-download\">Icon</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><span class=\"button primary disabled\">Disabled</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><span class=\"button disabled\">Disabled</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"major\">Form</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"fields\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-name\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"demo-name\" id=\"demo-name\" value=\"\" placeholder=\"Jane Doe\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-email\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"demo-email\" id=\"demo-email\" value=\"\" placeholder=\"jane@untitled.tld\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-category\">Category</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"demo-category\" id=\"demo-category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Manufacturing</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Shipping</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Administration</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Human Resources</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"demo-priority-low\" name=\"demo-priority\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-priority-low\">Low</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"demo-priority-high\" name=\"demo-priority\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-priority-high\">High</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"demo-copy\" name=\"demo-copy\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-copy\">Email me a copy</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"demo-human\" name=\"demo-human\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-human\">Not a robot</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"demo-message\">Message</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"demo-message\" id=\"demo-message\" placeholder=\"Enter your message\" rows=\"6\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" class=\"primary\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Reset\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"copyright\">&copy; Untitled. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BG -->\r\n");
      out.write("\t\t\t<div id=\"bg\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
